### ISSUE TITLE
Update AWS CRT to v0.29.14 or higher

### ISSUE THREAD

**Issue by adampoplawski** [quarkiverse/quarkus-amazon-services#1230] opened 2024-04-23 07:16 UTC
Hello
We have tested some of our applications with AWS CRT instead of Netty for DynamoDb. We are getting:

2024-04-08 11:18:42,231 ERROR [com.xxx.xxx.map.exc.GeneralServerExceptionMapper] (vert.x-eventloop-thread-1) java.lang.NullPointerException: Cannot invoke "java.lang.ClassLoader.getResources(String)" because "cl" is null

In POM https://github.com/quarkiverse/quarkus-amazon-services/blob/main/pom.xml I still see v0.29.13

This issue (https://github.com/awslabs/aws-crt-java/issues/451) seems to be potentially solved in
https://github.com/awslabs/aws-crt-java/pull/774/files

Is there an option to Update AWS CRT to v0.29.14 or higher, and maybe even ship it with Quarkus 3.10.0 release?
Thx for help
Adam

**Comment by scrocquesel** [comment] 2024-04-24 17:35
You should be able to specify the desired version explicitly by adding the dependency before Quarkus.

Are you experiencing the issue in development or testing mode? Could you provide a reproducer? We already have numerous tests for DynamoDB. It would be appreciated if your scenario could be included. You can find our existing tests at https://github.com/quarkiverse/quarkus-amazon-services/tree/main/integration-tests/src/main/java/io/quarkus/it/amazon/dynamodb

**Comment by scrocquesel** [comment] 2024-04-24 18:21
I'm fixing the PR #1224 to bump to the latest

**Comment by adampoplawski** [comment] 2024-04-24 18:36
Hello
@scrocquesel I will try to make reproducer, cannot share whole project, but maybe we will be able to find particular case.

**Comment by scrocquesel** [comment] 2024-05-05 16:32
Closing this. Reopen or create another one with the reproducer if the issue is not fixed

**Closed** 2024-05-05 16:32 UTC
