### ISSUE TITLE
GraalVM Substitution: DynamoDB enhanced client native image error

### ISSUE THREAD

**Issue by OmerShemesh** [quarkiverse/quarkus-amazon-services#610] opened 2023-03-21 13:05 UTC
Hi there,

while using the enhanced client i'm getting this error while executing a native image:
```
ERROR [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (NORMAL)) Failed to run lambda (NORMAL): java.lang.IllegalStateException: GraalVM Substitution: Unable to convert Constructor to MethodHandle
        at io.quarkus.amazon.dynamodb.enhanced.runtime.BeanTableSchemaSubstitutionImplementation.newObjectSupplierForClass(BeanTableSchemaSubstitutionImplementation.java:24)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.newObjectSupplierForClass(BeanTableSchema.java)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.createStaticTableSchema(BeanTableSchema.java:189)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:145)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.lambda$create$0(BeanTableSchema.java:135)
        at java.base@17.0.6/java.util.Map.computeIfAbsent(Map.java:1054)
        at java.base@17.0.6/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:135)
        at software.amazon.awssdk.enhanced.dynamodb.TableSchema.fromBean(TableSchema.java:84)
        at software.amazon.awssdk.enhanced.dynamodb.TableSchema.fromClass(TableSchema.java:128)
        at com.deliveries.common.dao.impl.BaseDaoImpl.findById(BaseDaoImpl.java:72)
        at com.deliveries.common.dao.impl.BaseDaoImpl.findByIdSync(BaseDaoImpl.java:133)
        at com.deliveries.common.dao.impl.BaseDaoImpl_ClientProxy.findByIdSync(Unknown Source)
        at com.deliveries.common.services.impl.BaseServiceImpl.findByIdSync(BaseServiceImpl.java:73)
        at com.deliveries.common.services.impl.SourceServiceImpl_ClientProxy.findByIdSync(Unknown Source)
        at com.deliveries.sanity.SanityCheckLambda.findSource(SanityCheckLambda.java:126)
        at com.deliveries.sanity.SanityCheckLambda.isDeliveryValid(SanityCheckLambda.java:62)
        at com.deliveries.sanity.SanityCheckLambda.handleRequest(SanityCheckLambda.java:44)
        at com.deliveries.sanity.SanityCheckLambda.handleRequest(SanityCheckLambda.java:22)
        at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:167)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:137)
        at java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.NoSuchMethodException: com.deliveries.common.models.parameters.Source.<init>()
        at java.base@17.0.6/java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.base@17.0.6/java.lang.Class.getConstructor(DynamicHub.java:2271)
        at io.quarkus.amazon.dynamodb.enhanced.runtime.BeanTableSchemaSubstitutionImplementation.newObjectSupplierForClass(BeanTableSchemaSubstitutionImplementation.java:21)
        ... 23 more
```

An example to one of my models:

```
@DynamoDbBean
@RegisterForReflection
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Source {

    private long id;

    private String name;

    private long externalId;

    @DynamoDbPartitionKey
    public long getId() {
        return id;
    }
    public String getName() {
        return name;
    }
    public long getExternalId() {
        return externalId;
    }
}

```

Has anyone faced this issue?

**Comment by scrocquesel** [comment] 2023-04-07 22:43
@OmerShemesh Which version of Quarkus / GraalVM  are you using ?

@knuspertante @hamburml  Any ideas ?

**Comment by hamburml** [comment] 2023-04-08 13:59
I am able to get the same error message when only using lombok `AllArgsConstructor` Annotation. Afaik enhanced client always needs a no args constructor, see step 2 of https://aws.amazon.com/blogs/developer/introducing-enhanced-dynamodb-client-in-the-aws-sdk-for-java-v2/ 
The NoSuchMethodException also indicates that something is missing.

**Comment by knuspertante** [comment] 2023-05-16 14:26
Hey @OmerShemesh, 

can you pls provide a simple reproducer, then I will have a closer look? I can't reproduce this behaviour on the latest version. 

This Issue isn't new: https://github.com/aws/aws-sdk-java-v2/issues/2445#issuecomment-881955469

**Comment by hamburml** [comment] 2023-05-16 16:04
@knuspertante What you linked is a message from Nithanim who helped add enhanced client to this extension https://github.com/quarkiverse/quarkus-amazon-services/pull/488 The error message originates from https://github.com/quarkiverse/quarkus-amazon-services/blob/fb6b830b37e3d4fac76d815bdf20c3d13a908715/dynamodb-enhanced/runtime/src/main/java/io/quarkus/amazon/dynamodb/enhanced/runtime/BeanTableSchemaSubstitutionImplementation.java#L25

Nevertheless a reproducer would be nice :)

**Comment by knuspertante** [comment] 2023-05-17 08:04
Hey @hamburml,

thanks for that info. I already thought something like that ;-) Therefore I tried to reproduced this error with 

 https://github.com/knuspertante/quarkus-amazon-services/blob/66b91525e9972219b50ed90d158b5dc616380a79/integration-tests/src/main/java/io/quarkus/it/amazon/dynamodb/enhanced/DynamoDBExampleTableEntry.java#LL17C1-L23C1

The tests works in JVM and Native mode. That means the conversion of the constructor(s) to MethodHandle works well for `class io.quarkus.it.amazon.dynamodb.enhanced.DynamoDBExampleTableEntry`and `class software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider` in my case.

**Comment by knuspertante** [comment] 2023-06-02 08:57
@scrocquesel I think this could be closed, since no reaction from @OmerShemesh and works just fine in test?

**Comment by scrocquesel** [comment] 2023-06-05 20:29
@OmerShemesh Closing as non-reproducible. If you are still experiencing the issue, please open a new issue and provide a reproducer.

**Closed by scrocquesel** 2023-06-05 20:29 UTC

**Comment by tusharjajodia** [comment] 2024-07-08 17:05
I am facing the same issue. Anyone else ?
