### ISSUE TITLE
Trouble returning file types from S3

### ISSUE THREAD

**Issue by mikeymop** [quarkiverse/quarkus-amazon-services#157] opened 2022-05-17 17:14 UTC
Hello,
I am following along with Quarkus [guides](https://quarkiverse.github.io/quarkiverse-docs/quarkus-amazon-services/dev/amazon-s3.html#_going_asynchronous) on Amazon S3.

Based off of these examples I am trying to write a REST endpoint that returns objects of type
 * 'application/pdf'
 * 'image/jpeg'
 * 'image/png'
 * 'text/csv'
 * 'text/plain'

When using the example directly (adapted to my code) it looks a bit a like this:

```java
@Override
public Uni<Response> getFile(String bucket, String objectKey, String filename) {
    return Uni.createFrom()
        .completionStage(() -> s3.getObject(buildGetRequest(bucket, objectKey), AsyncResponseTransformer.toBytes()))
        .onItem()
        .transform(object -> Response.ok(object.asUtf8String())
            .type(object.response().contentType())
            .header("Content-Disposition", "attachment;filename=" + filename)
            .header("Content-Type", object.response().contentType()).build());
    }
```

This results in the following error: 
```
java.io.UncheckedIOException: Cannot encode string
```

I double checked and the images do display and are valid when viewing them in the ecs browser gui directly. The images are uploaded from a browser so I expect them to be in UTF8 already.

### Things I have tried

I experimented with trying `object.asInputStream()` and `object.asByteBuffer()` and these to successfully return the object as a file to the browser downloading the file.
However once viewing the image that was downloaded I found that they are twice the size as the original image and that they are invalid pngs / jpegs.

When trying to download a pdf with the same code, I get a pdf back that is also larger, and it displays in a browser however the content is gone.

Ultimately I have found that the only format I can get back using this code is plain text.

### Things I have tried

 * Adding `@Produces( { "image/png", "image/jpeg", "application/pdf", "text/csv", "text/plain" })` to the rest resource
 * Using different data streams by swapping out `object.asUtf8String()` for other methods.
 * Manually setting the `type` on `Response` eg: `.type(object.response().contentType())`
 * Verifying I am on the latest Quarkus version and the relevant Quarkus extensions and libraries are up to date.
 * Visiting the rest resource directly in the browser (shows an invalid page instead of a pdf or image).

Any input is appreciated.

**Comment by scrocquesel** [comment] 2023-01-21 00:02
Cannot reproduce with `AsyncResponseTransformer.toBytes` and `asInputStream `or `asByteArray`. You cannot use `asByteBuffer` as restEasy do not know how to convert it to a body response.

It also works using `AsyncResponseTransformer.toBlockingInputStream()`.

```java
return Uni.createFrom()
                .completionStage(() -> s3.getObject(buildGetRequest(objectKey), AsyncResponseTransformer.toBlockingInputStream()))
                .onItem()
                .transform(object -> Response.ok(object)
                        .header("Content-Disposition", "attachment;filename=" + objectKey)
                        .header("Content-Type", object.response().contentType()).build());
```

@mikeymop  Do you still have an issue or can you provide a reproductible QuarkusTest that demonstrate the bug ?

**Comment by scrocquesel** [comment] 2023-04-12 20:11
Closing, feel free to reopen an issue if needed

**Closed by scrocquesel** 2023-04-12 20:11 UTC
